/**
 * Catálogo Maestro de Productos - Dietética NUTS
 * Información extraída directamente de la lista de precios oficial
 * Contacto: WhatsApp 1151315757 | Instagram @nuts.food.ba
 */

const NUTS_CONFIG = {
    storeName: "NUTS",
    tagline: "Dietética & Almacén Saludable",
    whatsapp: "5491151315757",
    whatsappDisplay: "11 5131-5757",
    instagram: "nuts.food.ba",
    minOrderAmount: 20000, // Mínimo de compra requerido por NUTS
    freeShippingThreshold: 40000, // Envío gratis a partir de $40.000
    shippingBenefit: "Entregas a domicilio SIN CARGO a partir de $40.000",
    paymentMethods: "Efectivo o Transferencia",
    currencySymbol: "$",
    adminPin: "1234" // PIN por defecto para el modo administrador del dueño
};

const CATEGORIES = [
    { id: "all", name: "Todos los Productos", icon: "sparkles", count: 0 },
    { id: "combos", name: "Combos Especiales", icon: "package", count: 4, featured: true },
    { id: "frutos-secos", name: "Frutos Secos", icon: "nut", count: 12 },
    { id: "mixes", name: "Nuestros Mixes", icon: "layers", count: 6 },
    { id: "granolas-snacks", name: "Granolas & Snacks", icon: "cookie", count: 4 },
    { id: "deshidratados", name: "Frutos Deshidratados", icon: "sun", count: 9 },
    { id: "harinas", name: "Harinas y Féculas", icon: "wheat", count: 7 },
    { id: "semillas", name: "Semillas Sin TACC", icon: "sprout", count: 8 },
    { id: "legumbres", name: "Legumbres y Granos", icon: "bean", count: 7 },
    { id: "cereales", name: "Cereales & Almohaditas", icon: "bowl", count: 7 },
    { id: "almacen", name: "Almacén Natural", icon: "store", count: 16 },
    { id: "suplementos", name: "Suplementos Naturales", icon: "heart-pulse", count: 5 },
    { id: "varios", name: "Varios & Repostería", icon: "utensils", count: 10 }
];

const PRODUCTS_DATA = [
    // ==========================================
    // COMBOS ESPECIALES DEL MES (Flyer 1)
    // ==========================================
    {
        id: "combo-1",
        name: "Combo 1 - Despensa Saludable",
        category: "combos",
        categoryName: "Combos Especiales",
        priceType: "combo",
        price: 50000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        imageIcon: "box",
        description: "El pack más completo para renovar tu despensa con básicos de primera calidad.",
        itemsIncluded: [
            "1 kg Mix Premium (solo secos)",
            "1 kg Lentejas seleccionadas",
            "500 g Coco Rallado aromático",
            "500 g Mix 4 semillas (lino, chía, sésamo, girasol)",
            "500 g Maní sin sal tostado",
            "1 kg Miel pura de campo",
            "500 cc Aceite de Oliva Extra Virgen"
        ],
        tags: ["combo", "despensa", "ahorro", "básicos"]
    },
    {
        id: "combo-2",
        name: "Combo 2 - Keto & Desayunos Fit",
        category: "combos",
        categoryName: "Combos Especiales",
        priceType: "combo",
        price: 52000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        imageIcon: "flame",
        description: "Ideal para dietas cetogénicas, desayunos proteicos y repostería saludable baja en carbohidratos.",
        itemsIncluded: [
            "1 kg Harina de Almendras pura",
            "500 g Almendras seleccionadas",
            "750 g Granola Almendra Crunch",
            "1 kg Mix Completo (secos y pasas)",
            "360 cc Pasta de Maní natural",
            "440 cc Dulce de Leche sin azúcar"
        ],
        tags: ["combo", "keto", "fit", "proteico", "desayuno"]
    },
    {
        id: "combo-3",
        name: "Combo 3 - Especial Energía",
        category: "combos",
        categoryName: "Combos Especiales",
        priceType: "combo",
        price: 53000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        imageIcon: "zap",
        description: "Un balance perfecto entre frutos secos premium, granos integrales y grasas saludables.",
        itemsIncluded: [
            "1 kg Mix Premium (solo frutos secos)",
            "360 cc Pasta de Maní natural",
            "1 kg Arroz Yamaní integral",
            "500 g Mix 4 Semillas",
            "750 g Granola Crunch",
            "500 g Pasas negras de uva",
            "500 cc Aceite de Oliva virgen"
        ],
        tags: ["combo", "energia", "mix", "fibra"]
    },
    {
        id: "combo-4",
        name: "Combo 4 - Full Frutos & Almacén",
        category: "combos",
        categoryName: "Combos Especiales",
        priceType: "combo",
        price: 56000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        imageIcon: "award",
        description: "El combo estrella: máxima variedad en frutos enteros, miel pura de campo y despensa.",
        itemsIncluded: [
            "500 g Nuez Mariposa extra clara",
            "500 g Almendras seleccionadas",
            "500 g Pasas negras de uva",
            "500 g Mix 4 Semillas",
            "500 g Coco Rallado fino",
            "1 kg Lentejas seleccionadas",
            "360 cc Pasta de Maní natural",
            "1 kg Miel pura de campo",
            "500 cc Aceite de Oliva virgen"
        ],
        tags: ["combo", "full", "premium", "nuez", "miel"]
    },

    // ==========================================
    // FRUTOS SECOS (Flyer 2)
    // ==========================================
    {
        id: "nuez-mariposa",
        name: "Nuez Mariposa (Cosecha 2026)",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 24000,
        price500g: 12000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Nuez mariposa extra clara fresca de última cosecha. Ricas en Omega 3 y antioxidantes.",
        tags: ["nuez", "mariposa", "omega3", "sin tacc", "cerebro"]
    },
    {
        id: "almendra-non-pareil",
        name: "Almendra Non Pareil",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 31000,
        price500g: 15500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "La variedad más fina de almendra: piel fina, textura crocante y sabor suave insuperable.",
        tags: ["almendra", "non pareil", "sin tacc", "crocante"]
    },
    {
        id: "almendra-guara",
        name: "Almendra Guara",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 27000,
        price500g: 13500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Almendra mediterránea de excelente calibre, ideal para tostados y consumo diario.",
        tags: ["almendra", "guara", "sin tacc"]
    },
    {
        id: "castana-caju-natural",
        name: "Castaña de Cajú Natural",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 20000,
        price500g: 10000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Cajú cremoso y tierno sin tostar ni salar. Ideal para quesos veganos, repostería o snacks.",
        tags: ["caju", "castaña", "natural", "vegano", "sin tacc"]
    },
    {
        id: "castana-caju-tostada",
        name: "Castaña de Cajú Tostada",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 21800,
        price500g: 10900,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Cajú con un tostado dorado perfecto que resalta su aroma y crocancia.",
        tags: ["caju", "castaña", "tostada", "sin tacc"]
    },
    {
        id: "castana-para",
        name: "Castaña de Pará (Nuez de Brasil)",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 47000,
        price500g: 23500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "La mayor fuente natural de selenio. 2 o 3 al día aportan la dosis requerida para el organismo.",
        tags: ["castaña", "para", "brasil", "selenio"]
    },
    {
        id: "avellana",
        name: "Avellana Entera Pelada",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 47000,
        price500g: 23500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Avellanas enteras de sabor dulce e intenso. Clave para untables y chocolates saludables.",
        tags: ["avellana", "sin tacc", "reposteria"]
    },
    {
        id: "pistacho-salado",
        name: "Pistacho Salado (con cáscara)",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 46000,
        price500g: 23000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Pistachos tostados al punto justo con un toque de sal marina. El snack gourmet por excelencia.",
        tags: ["pistacho", "salado", "gourmet", "sin tacc"]
    },
    {
        id: "mani-pelado",
        name: "Maní Tostado (Con o Sin Sal)",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 5000,
        price500g: 2500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        options: ["Sin Sal", "Con Sal"],
        description: "Maní tostado crujiente de primera calidad. Podés elegir la opción con o sin sal añadida.",
        tags: ["mani", "economico", "proteina", "snack"]
    },
    {
        id: "maiz-frito-salado",
        name: "Maíz Frito Salado",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 13000,
        price500g: 6500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Maíz tostado super crujiente y saladito, ideal para picadas y aperitivos.",
        tags: ["maiz", "frito", "salado", "picada"]
    },
    {
        id: "mani-japones",
        name: "Maní Japonés (Sabor Original)",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 7000,
        price500g: 3500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Maní recubierto con una capa crocante de harina de trigo y salsa de soja tradicional.",
        tags: ["mani", "japones", "crocante", "snack"]
    },
    {
        id: "garrapinada-mani",
        name: "Garrapiñada de Maní",
        category: "frutos-secos",
        categoryName: "Frutos Secos",
        priceType: "weight",
        price1kg: 5000,
        price500g: 2500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Maní crocante caramelizado artesanalmente con azúcar dorada y esencia de vainilla.",
        tags: ["garrapiñada", "mani", "dulce", "artesanal"]
    },

    // ==========================================
    // NUESTROS MIXES (Flyer 5)
    // ==========================================
    {
        id: "mix-frutos-premium",
        name: "Mix Frutos Premium (Solo Secos)",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 26000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Nuez entera, castaña de cajú, almendras y avellana seleccionada. Cero pasas, 100% frutos secos nobles.",
        tags: ["mix", "premium", "sin tacc", "nuez", "caju", "avellana", "almendra"]
    },
    {
        id: "mix-frutos-secos",
        name: "Mix Frutos Secos Clásico",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 18000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Nuez entera, castaña de cajú, almendras y maní tostado. Equilibrio ideal de sabor y energía.",
        tags: ["mix", "frutos secos", "sin tacc", "mani", "almendra"]
    },
    {
        id: "mix-con-pasas",
        name: "Mix Con Pasas Negras",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 16000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Nuez entera, castaña de cajú, almendras y pasas de uva negras dulces sin semilla.",
        tags: ["mix", "pasas", "sin tacc", "dulce"]
    },
    {
        id: "mix-tropical",
        name: "Mix Tropical Exótico",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 15000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Nuez entera, cajú, almendras, pasas de uva, chips de banana crocante y ananá dulce en cubos.",
        tags: ["mix", "tropical", "banana", "anana", "frutal"]
    },
    {
        id: "mix-completo",
        name: "Mix Completo Tradicional",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 13000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Nuez entera, cajú, almendra, maní tostado, pasas de uva rubias y pasas negras.",
        tags: ["mix", "completo", "sin tacc", "economico"]
    },
    {
        id: "mix-salado",
        name: "Mix Salado Especial",
        category: "mixes",
        categoryName: "Nuestros Mixes",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 10000,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Maní salado, maíz frito crocante, almendra, semillas de zapallo y semillas de girasol tostadas.",
        tags: ["mix", "salado", "picada", "maiz", "zapallo"]
    },

    // ==========================================
    // GRANOLAS & SNACKS (Flyer 5)
    // ==========================================
    {
        id: "granola-almendra-crunch",
        name: "Granola Almendra Crunch (Homemade)",
        category: "granolas-snacks",
        categoryName: "Granolas & Snacks",
        priceType: "unit",
        unitLabel: "x 750 grs.",
        priceUnit: 13000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Receta casera crocante: copos de avena, almendras tostadas, miel pura de campo, semillas de girasol y coco rallado.",
        tags: ["granola", "crunch", "almendra", "homemade", "desayuno"]
    },
    {
        id: "granola-cereal-light",
        name: "Granola Cereal Light (Homemade)",
        category: "granolas-snacks",
        categoryName: "Granolas & Snacks",
        priceType: "unit",
        unitLabel: "x 750 grs.",
        priceUnit: 13000,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Elaboración artesanal liviana: avena, copos crocantes, pasas de uva, almendras, maní, manzana deshidratada y mix de semillas.",
        tags: ["granola", "light", "manzana", "fibra"]
    },
    {
        id: "snack-kids-nuts",
        name: "Snack Kids Nuts",
        category: "granolas-snacks",
        categoryName: "Granolas & Snacks",
        priceType: "unit",
        unitLabel: "x 750 grs.",
        priceUnit: 7800,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Snack divertido y nutritivo: copos sin azúcar, quinoa pop, aritos de miel, maní garrapiñado, rocklets de chocolate, cajú tostado y girasol pelado.",
        tags: ["snack", "kids", "rocklets", "quinoa pop", "niños"]
    },
    {
        id: "snack-work-nuts",
        name: "Snack Work Nuts Sin TACC",
        category: "granolas-snacks",
        categoryName: "Granolas & Snacks",
        priceType: "unit",
        unitLabel: "x 750 grs.",
        priceUnit: 7800,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "La energía justa para tu jornada laboral: copos sin azúcar, quinoa pop, almendra partida, cajú tostado, maní sin sal, semillas de girasol y zapallo.",
        tags: ["snack", "work", "sin tacc", "energia", "oficina"]
    },

    // ==========================================
    // FRUTOS DESHIDRATADOS (Flyer 2)
    // ==========================================
    {
        id: "fruta-escurrida",
        name: "Fruta Escurrida Glaseada",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 4800,
        price500g: 2400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Frutas surtidas en cubitos dulces. Especial para budines, panes dulces y repostería festiva.",
        tags: ["fruta", "escurrida", "pan dulce", "sin tacc"]
    },
    {
        id: "pasa-negra-jumbo",
        name: "Pasa Negra Jumbo (Sin Semilla)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 8600,
        price500g: 4300,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Uvas pasas de gran tamaño, carnosas, dulces y tiernas sin semilla.",
        tags: ["pasas", "jumbo", "negra", "sin tacc"]
    },
    {
        id: "pasa-negra-flame",
        name: "Pasa Negra Flame (Sin Semilla)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 6000,
        price500g: 3000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Pasas negras seleccionadas de tamaño estándar, ideales para cocinar o acompañar cereales.",
        tags: ["pasas", "flame", "sin tacc"]
    },
    {
        id: "pasa-rubia",
        name: "Pasa Rubia Golden (Sin Semilla)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 12000,
        price500g: 6000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Pasas doradas de sabor refinado y toque ácido agradable. Deliciosas en ensaladas y platos agridulces.",
        tags: ["pasas", "rubias", "golden", "sin tacc"]
    },
    {
        id: "ciruela-bombom",
        name: "Ciruela Bombón (Sin Carozo)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 13000,
        price500g: 6500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Ciruelas deshidratadas tiernas, jugosas y sin carozo. Excelente aliada para la digestión natural.",
        tags: ["ciruela", "bombom", "fibra", "digestion", "sin tacc"]
    },
    {
        id: "datil-egipto",
        name: "Dátil Egipto (Con Carozo)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 9000,
        price500g: 4500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Dátiles dulces y melosos importados de Egipto. El endulzante natural favorito para recetas fit.",
        tags: ["datil", "egipto", "natural", "fit", "sin tacc"]
    },
    {
        id: "arandanos-rojos",
        name: "Arándanos Rojos Deshidratados (Cranberries)",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 21000,
        price500g: 10500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Arándanos rojos tiernos con equilibrio dulce y ácido. Potente fuente de antioxidantes y salud urinaria.",
        tags: ["arandano", "rojo", "cranberry", "antioxidante", "sin tacc"]
    },
    {
        id: "tomate-premium",
        name: "Tomate Seco Premium",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 19000,
        price500g: 9500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Tomates desecados al sol de aroma concentrado. Perfectos para hidratar en aceite de oliva y hierbas.",
        tags: ["tomate", "seco", "gourmet", "sin tacc"]
    },
    {
        id: "chips-banana",
        name: "Chips de Banana Deshidratada",
        category: "deshidratados",
        categoryName: "Frutos Deshidratados",
        priceType: "weight",
        price1kg: 15400,
        price500g: 7700,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Rodajas de banana crocantes y dulces, un snack energético y delicioso a cualquier hora.",
        tags: ["chips", "banana", "crocante", "snack"]
    },

    // ==========================================
    // HARINAS Y FÉCULAS (Flyer 2)
    // ==========================================
    {
        id: "harina-integral",
        name: "Harina Integral de Trigo",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 1800,
        price500g: 900,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Harina de molienda completa conservando el salvado y germen del trigo. Alta en fibra vegetal.",
        tags: ["harina", "integral", "fibra", "panaderia"]
    },
    {
        id: "harina-avena",
        name: "Harina de Avena (Importada)",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 3200,
        price500g: 1600,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Molienda fina de avena de máxima pureza, ideal para panqueques saludables y licuados.",
        tags: ["harina", "avena", "pancakes", "desayuno"]
    },
    {
        id: "harina-almendras",
        name: "Harina de Almendras (Con Piel)",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 7000,
        price500g: 3500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Almendras molidas 100% puras. Clave indiscutida para la dieta keto y recetas bajas en carbohidratos.",
        tags: ["harina", "almendra", "keto", "sin tacc", "low carb"]
    },
    {
        id: "harina-coco",
        name: "Harina de Coco (Importada)",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 8800,
        price500g: 4400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Harina aromática y suave obtenida de pulpa de coco desgrasada. Muy rica en fibra y libre de gluten.",
        tags: ["harina", "coco", "keto", "sin tacc"]
    },
    {
        id: "harina-garbanzo",
        name: "Harina de Garbanzo",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 1800,
        price500g: 900,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Harina proteica y nutritiva de garbanzos molidos. Esencial para fainá tradicional y rebozados crocantes.",
        tags: ["harina", "garbanzo", "faina", "proteica", "sin tacc"]
    },
    {
        id: "fecula-mandioca",
        name: "Fécula de Mandioca (Almidón)",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 3200,
        price500g: 1600,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "El ingrediente estrella e insustituible para preparar el auténtico chipá casero y panes de queso.",
        tags: ["fecula", "mandioca", "chipa", "sin tacc"]
    },
    {
        id: "fecula-maiz",
        name: "Fécula de Maíz (Tipo Maizena)",
        category: "harinas",
        categoryName: "Harinas y Féculas",
        priceType: "weight",
        price1kg: 2600,
        price500g: 1300,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Fécula ultra fina para espesar salsas, cremas o preparar alfajorcitos de maicena clásicos.",
        tags: ["fecula", "maiz", "alfajores", "sin tacc"]
    },

    // ==========================================
    // SEMILLAS SIN TACC (Flyer 3)
    // ==========================================
    {
        id: "mix-4-semillas",
        name: "Mix 4 Semillas (Lino, Chía, Sésamo y Girasol)",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 4600,
        price500g: 2300,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "La combinación justa de semillas para espolvorear sobre ensaladas, yogures, panes o tostadas.",
        tags: ["semillas", "mix", "chia", "lino", "sesamo", "girasol", "sin tacc"]
    },
    {
        id: "lino-marron",
        name: "Semillas de Lino Marrón",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 4400,
        price500g: 2200,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Excelentes para activar en agua y aprovechar su mucílago protector del sistema digestivo.",
        tags: ["lino", "semillas", "fibra", "omega3", "sin tacc"]
    },
    {
        id: "chia-premium",
        name: "Semillas de Chía Premium",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 9800,
        price500g: 4900,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Chía limpia seleccionada. Ideal para pudines hidratados con leche vegetal y mermelada.",
        tags: ["chia", "semillas", "pudding", "omega3", "sin tacc"]
    },
    {
        id: "sesamo-integral",
        name: "Semillas de Sésamo Integral",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 4600,
        price500g: 2300,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Fuente extraordinaria de calcio vegetal y minerales esenciales con piel intacta.",
        tags: ["sesamo", "integral", "calcio", "semillas", "sin tacc"]
    },
    {
        id: "sesamo-negro",
        name: "Semillas de Sésamo Negro",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 5000,
        price500g: 2500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: false, // Marcado Sin Stock en el flyer original
        description: "Sésamo negro aromático, muy usado en gastronomía asiática, sushi y decoración.",
        tags: ["sesamo", "negro", "sin stock", "sin tacc"]
    },
    {
        id: "girasol-pelado",
        name: "Semillas de Girasol Pelado",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 5000,
        price500g: 2500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Pipas de girasol peladas y tiernas, listas para consumir o tostar en sartén seca.",
        tags: ["girasol", "pipas", "semillas", "sin tacc"]
    },
    {
        id: "semillas-zapallo",
        name: "Semillas de Zapallo (Pebitas)",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 13000,
        price500g: 6500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Ricas en zinc y magnesio. Sabor suave y crocante inconfundible.",
        tags: ["zapallo", "pebitas", "zinc", "sin tacc"]
    },
    {
        id: "quinoa-lavada",
        name: "Quinoa Lavada Real",
        category: "semillas",
        categoryName: "Semillas Sin TACC",
        priceType: "weight",
        price1kg: 12000,
        price500g: 6000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Quinoa lista para cocinar sin sabor amargo. Proteína completa con todos los aminoácidos esenciales.",
        tags: ["quinoa", "pseudocereal", "proteina", "sin tacc"]
    },

    // ==========================================
    // LEGUMBRES Y GRANOS (Flyer 3)
    // ==========================================
    {
        id: "lenteja",
        name: "Lentejas Seleccionadas",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 4800,
        price500g: 2400,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Lentejas tiernas de cocción rápida. Aportan hierro, proteínas y carbohidratos complejos.",
        tags: ["lentejas", "legumbres", "hierro", "sin tacc"]
    },
    {
        id: "garbanzo",
        name: "Garbanzos Enteros",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 2800,
        price500g: 1400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Garbanzos secos de gran tamaño. Indispensables para hummus casero, guisos y ensaladas.",
        tags: ["garbanzo", "hummus", "legumbres", "sin tacc"]
    },
    {
        id: "poroto-negro",
        name: "Porotos Negros",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 2800,
        price500g: 1400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Porotos negros tradicionales para feijoada, burritos o ensaladas nutritivas.",
        tags: ["porotos", "negros", "legumbres", "sin tacc"]
    },
    {
        id: "poroto-alubia",
        name: "Porotos Alubia Blancos",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 3600,
        price500g: 1800,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Porotos blancos de textura suave y cremosa una vez cocidos. Clásicos para sopas y guisos.",
        tags: ["porotos", "alubia", "blancos", "sin tacc"]
    },
    {
        id: "arroz-yamani",
        name: "Arroz Yamaní Integral",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 3200,
        price500g: 1600,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "El arroz integral más noble: grano corto, sabor almendrado y textura masticable única.",
        tags: ["arroz", "yamani", "integral", "grano", "sin tacc"]
    },
    {
        id: "avena-tradicional",
        name: "Avena Arrollada Tradicional",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 3500,
        price500g: 1750,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Copos de avena entera arrollada para porridge, galletitas de avena y granolas caseras.",
        tags: ["avena", "tradicional", "porridge", "desayuno"]
    },
    {
        id: "avena-instantanea",
        name: "Avena Arrollada Instantánea",
        category: "legumbres",
        categoryName: "Legumbres y Granos",
        priceType: "weight",
        price1kg: 3500,
        price500g: 1750,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Avena fina pre-cocida que se hidrata al instante con leche, yogur o agua tibia.",
        tags: ["avena", "instantanea", "rapido", "desayuno"]
    },

    // ==========================================
    // VARIOS Y REPOSTERÍA (Flyer 3)
    // ==========================================
    {
        id: "soja-texturizada",
        name: "Soja Texturizada Fina",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 3400,
        price500g: 1700,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Excelente sustituto vegetal de la carne picada para empanadas, salsas boloñesas y rellenos.",
        tags: ["soja", "texturizada", "vegano", "sin tacc"]
    },
    {
        id: "bicarbonato-sodio",
        name: "Bicarbonato de Sodio Puro",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 3000,
        price500g: 1500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Bicarbonato de sodio grado alimentario para repostería, limpieza y salud digestiva.",
        tags: ["bicarbonato", "sodio", "reposteria", "sin tacc"]
    },
    {
        id: "rocklets-arcor",
        name: "Confites Rocklets (Arcor)",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 27000,
        price500g: 13500,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Coloridos botones de chocolate con leche confitados de marca Arcor.",
        tags: ["rocklets", "chocolate", "confites", "dulce", "sin tacc"]
    },
    {
        id: "coco-rallado",
        name: "Coco Rallado Blanco",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 12600,
        price500g: 6300,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Coco rallado aromático y natural sin azúcar añadido. Clave en alfajores de maicena.",
        tags: ["coco", "rallado", "reposteria", "sin tacc"]
    },
    {
        id: "chips-chocolate",
        name: "Chips de Chocolate Semiamargo",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 14200,
        price500g: 7100,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Gotas de chocolate semiamargo horneables para muffins, cookies y budines.",
        tags: ["chocolate", "chips", "cookies", "sin tacc"]
    },
    {
        id: "cacao-amargo",
        name: "Cacao Amargo Puro en Polvo",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 18000,
        price500g: 9000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Cacao 100% puro alcalinizado sin azúcar. Sabor a chocolate profundo e intenso.",
        tags: ["cacao", "amargo", "puro", "keto", "sin tacc"]
    },
    {
        id: "azucar-mascabo",
        name: "Azúcar Mascabo Integral 'Balaju'",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 6800,
        price500g: 3400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Azúcar integral no refinada de caña. Conserva todas las melazas, minerales y aroma acaramelado.",
        tags: ["azucar", "mascabo", "balaju", "integral", "sin tacc"]
    },
    {
        id: "azucar-impalpable",
        name: "Azúcar Impalpable",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 3200,
        price500g: 1600,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Azúcar pulverizada finísima para glaseados, cremas y decoración de tortas.",
        tags: ["azucar", "impalpable", "glase", "sin tacc"]
    },
    {
        id: "polvo-hornear",
        name: "Polvo para Hornear (Leudante)",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "weight",
        price1kg: 7800,
        price500g: 3900,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Leudante químico de doble acción para lograr bizcochuelos esponjosos y panes aireados.",
        tags: ["polvo", "hornear", "leudante", "sin tacc"]
    },
    {
        id: "pancakes-granger",
        name: "Pancakes Proteicos 'Granger' 400g",
        category: "varios",
        categoryName: "Varios & Repostería",
        priceType: "unit",
        unitLabel: "x unid.",
        priceUnit: 14500,
        price: 14500,
        isSinTacc: true,
        isNew: true,
        isFeatured: true,
        inStock: true,
        description: "Premezcla lista para cocinar pancakes altos en proteína, sin harinas refinadas y libres de gluten.",
        tags: ["pancakes", "proteicos", "granger", "nuevo", "sin tacc"]
    },

    // ==========================================
    // CEREALES & ALMOHADITAS (Flyer 4)
    // ==========================================
    {
        id: "barrita-cereal-x3",
        name: "Barrita de Cereal x3 Unidades ('Tenés que probarlas')",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x pack 3 unid.",
        priceUnit: 7200,
        price: 7200,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Pack de 3 barritas artesanales crocantes y deliciosas sin TACC. ¡Una tentación saludable!",
        tags: ["barrita", "cereal", "pack", "snack", "sin tacc"]
    },
    {
        id: "almohaditas-500g",
        name: "Almohaditas Rellenas x 500g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 5000,
        price: 5000,
        isSinTacc: false,
        isNew: false,
        isFeatured: true,
        inStock: true,
        options: ["Frutilla", "Avellana"],
        description: "Cereal crujiente relleno con crema deliciosa. Elegí tu sabor favorito: Frutilla o Avellana.",
        tags: ["almohaditas", "rellenas", "frutilla", "avellana", "cereales"]
    },
    {
        id: "copos-azucarados-500g",
        name: "Copos de Maíz Azucarados x 500g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 3500,
        price: 3500,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Clásicos copos de maíz crocantes escarchados con una capa sutil de azúcar.",
        tags: ["copos", "maiz", "azucarados", "cereales"]
    },
    {
        id: "copos-sin-azucar-500g",
        name: "Copos de Maíz Sin Azúcar x 500g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 3000,
        price: 3000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Copos tostados 100% maíz natural sin azúcar añadido ni edulcorantes. Sin TACC.",
        tags: ["copos", "sin azucar", "maiz", "sin tacc"]
    },
    {
        id: "fibras-salvado-500g",
        name: "Fibras de Salvado x 500g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 3800,
        price: 3800,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Bastoncitos de fibra crocante para sumar a yogures y regular el tránsito digestivo.",
        tags: ["fibras", "salvado", "digestion", "sin tacc"]
    },
    {
        id: "aritos-500g",
        name: "Aritos de Cereal x 500g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 4800,
        price: 4800,
        isSinTacc: false,
        isNew: false,
        isFeatured: false,
        inStock: true,
        options: ["Frutales", "Miel"],
        description: "Aritos crocantes y sabrosos para meriendas alegres. Opciones disponibles: Frutales o Miel.",
        tags: ["aritos", "miel", "frutales", "cereales"]
    },
    {
        id: "quinoa-pop-250g",
        name: "Quinoa Pop Inflada x 250g",
        category: "cereales",
        categoryName: "Cereales & Almohaditas",
        priceType: "unit",
        unitLabel: "x 250 grs.",
        priceUnit: 2900,
        price: 2900,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Granos de quinoa inflados livianos como una nube. Ideales para barritas caseras o con yogur.",
        tags: ["quinoa", "pop", "inflada", "sin tacc"]
    },

    // ==========================================
    // ALMACÉN NATURAL SIN TACC (Flyer 4)
    // ==========================================
    {
        id: "hibiscus-flor",
        name: "Hibiscus (Flor de Jamaica) 250g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 250 grs.",
        priceUnit: 5200,
        price: 5200,
        isSinTacc: true,
        isNew: true,
        isFeatured: true,
        inStock: true,
        description: "Flores secas de hibiscus para infusiones refrescantes, digestivas y diuréticas de intenso color rubí.",
        tags: ["hibiscus", "flor de jamaica", "infusion", "nuevo", "sin tacc"]
    },
    {
        id: "mantequilla-mani-nina",
        name: "Mantequilla de Maní 'NINA' 360cc",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 360 cc",
        priceUnit: 4400,
        price: 4400,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "100% maní tostado y triturado a la perfección. Sin aceites añadidos, sin azúcar, sin conservantes.",
        tags: ["mantequilla", "mani", "nina", "pasta", "sin tacc"]
    },
    {
        id: "ghee-clarificada",
        name: "Ghee Manteca Clarificada 300cc",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 300 cc",
        priceUnit: 15000,
        price: 15000,
        isSinTacc: true,
        isNew: true,
        isFeatured: true,
        inStock: true,
        description: "Oro líquido ayurvédico: manteca clarificada libre de caseína y lactosa, de alto punto de humo.",
        tags: ["ghee", "manteca", "clarificada", "ayurveda", "nuevo", "sin tacc"]
    },
    {
        id: "aceite-coco-cosaco",
        name: "Aceite de Coco Neutro 'COSACO' 360cc",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 360 cc",
        priceUnit: 8200,
        price: 8200,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Aceite de coco sin aroma ni sabor a coco. Ideal para cocinar y freír de forma saludable.",
        tags: ["aceite", "coco", "neutro", "cosaco", "keto", "sin tacc"]
    },
    {
        id: "aceite-oliva-blend",
        name: "Aceite de Oliva Virgen Blend (Vidrio) 500cc",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 cc",
        priceUnit: 8000,
        price: 8000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Aceite de oliva de corte virgen en botella de vidrio económica. Excelente calidad para todos los días.",
        tags: ["aceite", "oliva", "blend", "vidrio", "sin tacc"]
    },
    {
        id: "aceite-oliva-fratoio",
        name: "Aceite Oliva Virgen Extra 'Noble Lur' Fratoio 500cc",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 cc",
        priceUnit: 15500,
        price: 15500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Línea premium de primera prensada en frío con aceitunas Fratoio seleccionadas. Botella de vidrio oscuro.",
        tags: ["aceite", "oliva", "extra virgen", "noble lur", "gourmet", "sin tacc"]
    },
    {
        id: "yerba-kalena-500g",
        name: "Yerba Mate 'Kalena' Tradicional 500g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 6000,
        price: 6000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Secanza tradicional tipo barbacuá con estacionamiento natural prolongado. No produce acidez.",
        tags: ["yerba", "kalena", "mate", "barbacua", "sin tacc"]
    },
    {
        id: "yerba-kalena-despalada",
        name: "Yerba Mate 'Kalena' Despalada 500g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 6000,
        price: 6000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Yerba con mínimo contenido de palo (máxima hoja pura). Mate intenso y rendidor.",
        tags: ["yerba", "kalena", "despalada", "mate", "sin tacc"]
    },
    {
        id: "yerba-roapipo-organica",
        name: "Yerba Mate Orgánica 'Roapipó' Suave 500g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 5800,
        price: 5800,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Certificación orgánica de Misiones. Sabor suave y amable con el estómago.",
        tags: ["yerba", "roapipo", "organica", "suave", "sin tacc"]
    },
    {
        id: "sal-rosa-himalaya",
        name: "Sal Rosa Fina del Himalaya 500g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 3400,
        price: 3400,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Sal mineral de montaña pura sin refinar ni aditivos artificiales. Rica en 84 oligoelementos.",
        tags: ["sal", "rosa", "himalaya", "minerales", "sin tacc"]
    },
    {
        id: "sal-marina-macrozen",
        name: "Sal Marina Fina 'Macrozen' 500g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 2800,
        price: 2800,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Sal pura obtenida por evaporación solar de agua marina. Sin conservantes ni blanqueadores.",
        tags: ["sal", "marina", "macrozen", "natural", "sin tacc"]
    },
    {
        id: "stevia-hojas-250g",
        name: "Stevia en Hojas Puras 250g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 250 grs.",
        priceUnit: 9000,
        price: 9000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Hojas secas de Stevia Rebaudiana entera para endulzar infusiones directamente con la planta.",
        tags: ["stevia", "hojas", "endulzante", "natural", "sin tacc"]
    },
    {
        id: "stevia-liquida-jual",
        name: "Stevia Líquida 'Jual' 200ml",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 200 ml",
        priceUnit: 8200,
        price: 8200,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Endulzante natural concentrado en gotas. No deja regusto amargo y rinde cientos de tazas.",
        tags: ["stevia", "liquida", "jual", "cero calorias", "sin tacc"]
    },
    {
        id: "miel-de-campo",
        name: "Miel Pura de Campo 1 Kg",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 1 Kg",
        priceUnit: 9000,
        price: 9000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Miel cruda de flores de campo, no pasteurizada. Conserva intactas todas sus enzimas y propiedades.",
        tags: ["miel", "campo", "pura", "artesanal", "sin tacc"]
    },
    {
        id: "dulce-leche-kony",
        name: "Dulce de Leche 'Kony' con Stevia x 440g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 440 grs.",
        priceUnit: 8500,
        price: 8500,
        isSinTacc: true,
        isNew: true,
        isFeatured: true,
        inStock: true,
        description: "Sin azúcar agregada, endulzado 100% con stevia natural. El sabor clásico del dulce de leche sin culpas.",
        tags: ["dulce de leche", "kony", "stevia", "sin azucar", "nuevo", "sin tacc"]
    },
    {
        id: "mermelada-kony",
        name: "Mermelada 'Kony' con Stevia x 360g",
        category: "almacen",
        categoryName: "Almacén Natural",
        priceType: "unit",
        unitLabel: "x 360 grs.",
        priceUnit: 8000,
        price: 8000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        options: ["Arándano", "Durazno"],
        description: "Fruta seleccionada reducida en calorías con stevia. Elegí tu sabor: Arándano o Durazno.",
        tags: ["mermelada", "kony", "stevia", "arandano", "durazno", "sin tacc"]
    },

    // ==========================================
    // SUPLEMENTOS NATURALES SIN TACC (Flyer 4)
    // ==========================================
    {
        id: "maca-kallpa-500g",
        name: "Maca Tradicional 'Kallpa' 500g",
        category: "suplementos",
        categoryName: "Suplementos Naturales",
        priceType: "unit",
        unitLabel: "x 500 grs.",
        priceUnit: 2500,
        price: 2500,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Raíz andina adaptógena que combate el cansancio físico y mental, aportando vitalidad.",
        tags: ["maca", "kallpa", "energia", "adaptogeno", "sin tacc"]
    },
    {
        id: "maca-negra-150g",
        name: "Maca Negra Peruana 150g",
        category: "suplementos",
        categoryName: "Suplementos Naturales",
        priceType: "unit",
        unitLabel: "x 150 grs.",
        priceUnit: 2000,
        price: 2000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "La variedad más potente de maca para rendimiento físico, resistencia deportiva y concentración.",
        tags: ["maca", "negra", "rendimiento", "fuerza", "sin tacc"]
    },
    {
        id: "harina-moringa-90g",
        name: "Harina de Moringa Pura 90g",
        category: "suplementos",
        categoryName: "Suplementos Naturales",
        priceType: "unit",
        unitLabel: "x 90 grs.",
        priceUnit: 1000,
        price: 1000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Conocida como el árbol de la vida por su altísima concentración de vitaminas A, C y minerales.",
        tags: ["moringa", "superalimento", "antioxidante", "sin tacc"]
    },
    {
        id: "colageno-hidrolizado-90g",
        name: "Colágeno Hidrolizado en Polvo 90g",
        category: "suplementos",
        categoryName: "Suplementos Naturales",
        priceType: "unit",
        unitLabel: "x 90 grs.",
        priceUnit: 1000,
        price: 1000,
        isSinTacc: true,
        isNew: false,
        isFeatured: true,
        inStock: true,
        description: "Péptidos de colágeno de máxima absorción para la salud de articulaciones, piel, cabello y uñas.",
        tags: ["colageno", "hidrolizado", "articulaciones", "piel", "sin tacc"]
    },
    {
        id: "harina-coca-90g",
        name: "Harina de Coca Instantánea 90g",
        category: "suplementos",
        categoryName: "Suplementos Naturales",
        priceType: "unit",
        unitLabel: "x 90 grs.",
        priceUnit: 1000,
        price: 1000,
        isSinTacc: true,
        isNew: false,
        isFeatured: false,
        inStock: true,
        description: "Energizante natural milenario con alto contenido en calcio bioasimilable.",
        tags: ["harina", "coca", "calcio", "energizante", "sin tacc"]
    }
];

// Asignar los conteos de categoría dinámicamente
CATEGORIES.forEach(cat => {
    if (cat.id === "all") {
        cat.count = PRODUCTS_DATA.length;
    } else {
        cat.count = PRODUCTS_DATA.filter(p => p.category === cat.id).length;
    }
});
